[package]
name = "embedded-test-std-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
libtest-mimic = "0.8.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
wait-timeout = "0.2.1"
