name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"

    steps:
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.8
    - name: rust cache
      uses: Swatinem/rust-cache@v2
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  msrv:
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.8

    - name: rust cache
      uses: Swatinem/rust-cache@v2

    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-binstall

    - name: "Installing cargo-udeps"
      run: cargo binstall -y --no-symlinks --force cargo-msrv

    - name: Check out repository code
      uses: actions/checkout@v4

    - name: "Verifying MSRV"
      run: cargo msrv verify
